FROM python:3.10
RUN pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy --system
COPY alembic.ini .
COPY startup.sh .
COPY app app
COPY alembic alembic
ENV PYTHONPATH=${PYTHONPATH}
ENV POSTGRES_URL=${POSTGRES_URL}
ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV REDIS_URL=${REDIS_URL}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV APP_PORT=${APP_PORT}
ENV APP_HOST=${APP_HOST}
ENV SECRET_KEY=${SECRET_KEY}
ENV AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
ENV AUTH0_PUBLIC_URL=${AUTH0_PUBLIC_URL}
ENV GMAIL_PASSWORD=${GMAIL_PASSWORD}
ENV GMAIL_USER=${GMAIL_USER}
ENV SSL_PORT=${SSL_PORT}
EXPOSE 8000
RUN ["chmod", "+x", "/startup.sh"]
CMD /startup.sh